### ISSUE TITLE
Game Jaguar JX220 too fast

### ISSUE THREAD

**Issue by albconde** [amigavision/AmigaVision#103]
Hi  thank you for your work , the last version 20230606 is awesome .
The game Jaguar JX200 is too fast , and afect the playability , the game is pal , is not the problem with other games who are launch in NTSC mode. 
In the whdload description of this games  say : 
version 1.5 (10.05.13) done by CFou!:
  - fix two access faults clearing chip memory 
  - fast memory used now to speed up the game on slow CPU
    (if game is too fast, you can use tooltype '[ExpChip](http://whdload.de/docs/en/opt.html#Exp)' to slow down game)

can you add this option when launch the game ?.

There are other games too fast like Niegel Mansell World Campionship and combo racer , but you can use "force pal" and play at correct speed.

Thank you in advance.
Cheers!

**Comment by Optiroc** [comment]
Jaguar XJ220 seems to run at the same speed regardless of the setting here. (I quite like that speed so I'm glad I don't have to make the judgment!)

I changed the two other racers to run in PAL by default.
