### ISSUE TITLE
Long game titles not showing up in favorites section when selected

### ISSUE THREAD

**Issue by SensibleInt** [amigavision/AmigaVision#105]
It seems when I select a game title that is over about the 30 characters to be a favorite, it does not appear in the new favorites section.
If I go to set it again, it confirms that it has already been selected as a favorite, even though it does not show up.

This happened with "Sensible Soccer: International Edition.."
And also happened with "The Simpsons: Bart vs. The Space Mutants"
Which makes me think it has to do with long game titles.

Thank you for your great work.
AmigaVision on my mister and pocket is a dream.

**Comment by Optiroc** [comment]
Good catch! 🤪

**Comment by SensibleInt** [comment]
Thank you!!
You're the best!
:)
