### ISSUE TITLE
Gods (Bitmap Brothers)

### ISSUE THREAD

**Issue by fmflex2drizzt** [amigavision/AmigaVision#107]
In the latest version of MegaAGS 2023.04.05 I've lost the ability to jump in the game Gods.  So I can't even get off the first ladder at the beginning of the game.  I went back to an older release (unsure of what version it is as it was already included with the Mister I bought) and the issue isn't there.  I can also load and play the game from adf images and can jump.

**Comment by Optiroc** [comment]
Gods should be configured with secondary button to jump, but to be honest I haven't double checked if that patch actually works in years.
