### ISSUE TITLE
Add configuration for Mousetrap, Robocop and Motorhead to Pocket

### ISSUE THREAD

**Issue by limi** [amigavision/AmigaVision#110]
Paul Calvey requested a configuration for Mousetrap to be added:

https://twitter.com/pcalvey77/status/1685333234500935680

There’s a WHDLoad configuration here:
https://whdload.de/games/Mousetrap.html

**Comment by limi** [comment]
Additionally, he’d like to see Robocop and Motorhead in the Pocket configuration

**Comment by Optiroc** [comment]
Done in 03b550a3d782fb73ee0c070759707e644f54b6ad
