### ISSUE TITLE
"Setup for Amiga hardware" clarifications

### ISSUE THREAD

**Issue by petmac** [amigavision/AmigaVision#112]
Hi,

Sorry about this, but I had a couple of questions about the install process for real hardware.

Currently, [Balena Etcher](https://www.balena.io/etcher) for Mac does not allow you to select a `.hdf` file. Renaming it to `.bin` allows Etcher to open the file, but is that correct?

What size of SD/CF card is required? I have a 4 GB CF card, which I thought would be the maximum the Amiga could address, but the disk image I found was 9.35 GB or so. Loading it up in FS-UAE shows one drive that's about 500 MB, and another that's about 3.5 GB, so I wondered if the disk image is artificially large.

Would it be possible to update the documentation to clarify?
Thanks

**Comment by limi** [comment]
From the commit above:

Simply locate the `games/Amiga/MegaAGS.hdf` file, and load that in your disk imaging tool of choice, and write it to the SD/CF card. If the file requester in the disk imaging tool does not allow you to select `.hdf` files, you may need to rename it to have a different extension, e.g. `.img`, `.bin` or similar.

If your HDF image contains every game in the database, you will need a 16GB CF/SD card. If you have a smaller card, you can make use of the configuration for the Analogue Pocket device, which will keep the selection under 4GB.
