### ISSUE TITLE
Filter

### ISSUE THREAD

**Issue by Manveru-V** [amigavision/AmigaVision#113]
Hi,
I'd like to share this with family & friends but would like a way to filter out the R-rated games (like all the Strip Poker games).
Is there an option to remove/hide them, either while AmigaVision is running or in the config?
Or, at least, can the default image be blacked out or just show the name of the game?

Thank you.

**Comment by Optiroc** [comment]
The menu system is (literally) a file browser, so the only way to do filtering is when you build the image.

**Comment by limi** [comment]
In other words, just delete the entries you want removed from the `AGS:` folders. The launcher does not do any run-time filtering, and it's unlikely to gain that feature in the near future.
