### ISSUE TITLE
Grapevine Disk Magazine Issue 3 not booting

### ISSUE THREAD

**Issue by zzedmore** [amigavision/AmigaVision#116]
Hi, Grapevine Issue 3 says you need a Meg upgrade to run it, lol ! Needs some memory adding to the Generic Slave I suppose ?

**Comment by Optiroc** [comment]
Ah, now I remember seeing this issue once and forgetting. Thanks. :) 

I suppose it exclusively looks for slow/trapdoor RAM... I wonder if that's possible to fake using the generic slave? Would you happen to know? ;)

**Comment by zzedmore** [comment]
I think any of Aladin's Generic game slaves will work as you can choose from different memory config slaves.

I used one of his games -
[Tapper-WHDL.zip](https://github.com/amigavision/AmigaVision/files/12370064/Tapper-WHDL.zip)

and quickly made this -
[Grapevine03.zip](https://github.com/amigavision/AmigaVision/files/12370072/Grapevine03.zip)

It seems to work. I had to put the whole contents of the ADF into the data directory (including the startup sequence). Maybe something to play around with !

**Comment by Optiroc** [comment]
Thanks!
