### ISSUE TITLE
PoliceQuest3 - De - MT32   (The German Version with MT32 Support) is still in english

### ISSUE THREAD

**Issue by Turricaner** [amigavision/AmigaVision#121]
PoliceQuest3DeMT32  is still the english version of the game.
You must add the following line:

language=49

to the file:

resource.cfg

so it looks like:

videoDrv=
soundDrv=mt32.drv
minHunk=220
minChip=240
kbdDrv=
mouseDrv=YES
language=49

**Comment by Optiroc** [comment]
Thanks for this, will fix!

**Comment by Turricaner** [comment]
Super 👍
