### ISSUE TITLE
Danger Freak  - is crashing after Title Screen

### ISSUE THREAD

**Issue by Turricaner** [amigavision/AmigaVision#122]
Danger Freak - is crashing after Title Screen ( here 68020 CPU ).
The newer Version 1.1 is working ( but without sound ).

**Comment by Optiroc** [comment]
Right. I reverted from v1.1 to v1.0 for some reason l've since forgotten... :) Let's go with v1.1 again. :D

**Comment by Turricaner** [comment]
Top 👍
