### ISSUE TITLE
15 Years of Fame Demo. Missing bottom of image

### ISSUE THREAD

**Issue by ransom1122** [amigavision/AmigaVision#129]
Using

AmigaVision-MegaAGS-2023.07.17

On muster fpga  this demo seems.to be cutt off on the bottom of the screen (TV is 1080p)

![received_862872398823078](https://github.com/amigavision/AmigaVision/assets/28079950/e30bcaa6-0cef-4fcb-8003-fa2853b0b477)

**Comment by limi** [comment]
I can’t reproduce this. 

It’s configured as 4×PAL here, which means no dynamic cropping is performed. (There’s a chance that this is one of the demos fixed after the 2023.07.17 release, but it works with the current settings in the GitHub repository, and will be included in the upcoming release)

Does it say “4×PAL” in the AGS entry?
