### ISSUE TITLE
Xenon NTSC PAL

### ISSUE THREAD

**Issue by ransom1122** [amigavision/AmigaVision#130]
Game is listed as NTSC in MegaAGS, game filename is xenon.lha which i believe is just renamed from Retroplay's Xenon_v1.2_0399.lha
This slave is PAL. There is no WHDload version of Xenon in NTSC, unless your using the Arcadia version Xenon_v0.2_Arcadia.lha

**Comment by limi** [comment]
This is intentional, as this is an Atari ST port. It should be in a different aspect (320×200 instead of 320×256) to get the correct looking pixel aspect ratio.

Are you seeing any other issues, graphical corruption or music issues? It seems to work fine for me.
