### ISSUE TITLE
Turrican PAL

### ISSUE THREAD

**Issue by ransom1122** [amigavision/AmigaVision#131]
It seems there some issues with the scaling on this game..

1. Intro legs of turrican are cut off
2. Ingame small part of thr bottom bit of the gfx are cut out

**Comment by limi** [comment]
It was off by about 3px, fixed. Note that we consider it an acceptable tradeoff that title screens etc that don’t affect gameplay will sometimes lose a few pixels, see the explanation and rationale here: https://amiga.vision/5x

(If we were not OK with this, a large number of games would not be able to run at 5× scale under 1080p/4K)
