### ISSUE TITLE
Tubular Worlds missing gfx above

### ISSUE THREAD

**Issue by ransom1122** [amigavision/AmigaVision#132]
All Video Modes Default, ForceNTSC, ForcePAL have missing gfx above
<img width="777" alt="aaa" src="https://github.com/amigavision/AmigaVision/assets/28079950/a38eab77-ded1-4202-9fd2-09198b0823e8">

**Comment by limi** [comment]
I can’t seem to reproduce this, works out of the box and does not cut off any graphics here. What version are you using?

**Comment by limi** [comment]
(Ignore the GitHub commit above, that was me fat-fingering the issue number for an unrelated fix)
