### ISSUE TITLE
Agony is cropped too much, might be good to include PAL version.

### ISSUE THREAD

**Issue by rsn8887** [amigavision/AmigaVision#134]
The Agony default crop or screenmode is wrong. This is a PAL game and should use all the lines. With the current version, the speed of the title music is also wrong (too slow) when forcing PAL. .adf floppy version works fine.

Here's one example

Correct image:
![image](https://github.com/amigavision/AmigaVision/assets/13071547/0cc5072e-b33e-4178-b119-35df354bba6a)

Current AmigaVision behavior (too few lines):
![image](https://github.com/amigavision/AmigaVision/assets/13071547/4889526d-b32d-49b7-813b-5ee4361b3f25)

A huge amount of the wonderful artwork on the top and bottom is missing!

This isn't the only image cropped too small, there is one at the beginning of every world. All those images are cropped wrong. These are some of the best pixel art images on the platform. They deserve to be seen fully. :)

It might be a good idea to include the PAL version, at least as an option.

**Comment by keungk** [comment]
can you check Switchblade 2 as well. That is far too cropped for me. try forcing PAL in the amiga vision options

**Comment by limi** [comment]
Addressed in https://github.com/amigavision/AmigaVision/commit/dbf4adb86389465087963f228801f6357a1f90de

Note that while we have made PAL the default now, it’s still using 5×PAL Dynamic Crop by default, and we consider it a reasonable tradeoff that some of the title screens are cut off a bit to prioritize 5× scale for gameplay, in line with the other configurations. If you don’t want Dynamic Crop, you can Force PAL in the Options, which will disable the crop/scale.

But music and speed should be consistent with what you expect in both cases now.
