### ISSUE TITLE
Please consider adding 9 Fingers and State of the Art by the demo group Spaceballs

### ISSUE THREAD

**Issue by psykoth** [amigavision/AmigaVision#140]
These were jaw dropping in their day with the use of vector graphics to show people dancing in their A500 demos.  I remember having my mind blown with what I was seeing at the time.  These are fun and high energy demos that take very little storage.

**Comment by limi** [comment]
They are both included in the demo section. Or are you asking to get them added to the Pocket version?

**Comment by psykoth** [comment]
Yes, I am referring to the Pocket version. Sorry, I should have been more specific.

**Comment by limi** [comment]
No problem. They are included in the upcoming release.
