### ISSUE TITLE
[Pocket][2023.12.25] Prehistorik crashes on startup

### ISSUE THREAD

**Issue by Buyukcaglar** [amigavision/AmigaVision#143]
Hi, Newly added game Prehistorik crashes on startup, just after WHDLoad screen. Is this core or configuration related?

Thanks,

![20231228_013148](https://github.com/amigavision/AmigaVision/assets/4595315/7d8a735e-d6a0-4ece-9742-8ad541c95814)

**Comment by limi** [comment]
Confirmed as not booting on the current Pocket core.

I tested it on the upcoming release of the Pocket core, and it works there. So once that releases, the game should work. Thanks for the report!
