### ISSUE TITLE
[Pocket][2023.12.25] Ruff n Tumble crashes on loading screen

### ISSUE THREAD

**Issue by ThreeM-MMM** [amigavision/AmigaVision#145]
**Bug Report - Ruff 'n' Tumble**

**Game:** Ruff 'n' Tumble

**Issue:** Upon launching Ruff 'n' Tumble, the game loads up to the loading screen. Ruff Rogers' head appears, but the game freezes at this point, preventing further progress into gameplay.

**Steps to Reproduce:**
1. Launch the Ruff 'n' Tumble game.
2. Observe the loading process until the character head freezes on the screen.

**Attempted Solutions:**
- Resetting the Amiga Core to default settings did not resolve the issue.

**Comment by limi** [comment]
Confirmed as not booting on the current Pocket core.

I tested it on the upcoming release of the Pocket core, and it works there. So once that releases, the game should work. Thanks for the report!
