### ISSUE TITLE
Space Taxi 3 corrupt engine and explosion sounds (AmigaVision MiSTer 20231225)

### ISSUE THREAD

**Issue by rsn8887** [amigavision/AmigaVision#151]
Thanks for adding Space Taxi 3. In the game, the engine sounds and explosions sounds are  missing completely or sometimes playing garbled.

I posted a later fixed version of the game here, still labeled 3.0, but all the files are newer:
https://files.coolatoms.org/SpaceTaxi3_fixed.lha

It can just be used instead of the existing version to fix the missing/garbled sound fx and some other problems (I tested this).

**Comment by limi** [comment]
Thanks for the link! Addressed in the upcoming release, re-open if there are still issues.
