### ISSUE TITLE
Nicky Boom and Nicky II should be PAL, not PAL60

### ISSUE THREAD

**Issue by rsn8887** [amigavision/AmigaVision#153]
Nicky Boom and Nicky II are French games, and should run in 50 Hz. They run way too fast with 60 Hz. The music is too fast, and therefore the calm atmosphere is lost. Faster is not better with such explorative games.

There's already a workaround, because the user can manually force PAL in the menu. But it is easy to forget this step.

**Comment by limi** [comment]
Fixed in https://github.com/amigavision/AmigaVision/commit/ecc9499321734cc51c6c9ad64e0c22f18549b4f0
