### ISSUE TITLE
Include Super Street Fighter II DX : The New Challengers AGA

### ISSUE THREAD

**Issue by KalElFrance** [amigavision/AmigaVision#154]
Would it be possible to include Super Street Fighter II DX which is an enhanced version of Super Street Fighter II : The New Challengers AGA ? See https://gamesnostalgia.com/game/super-street-fighter-ii

**Comment by limi** [comment]
I think that is the one that’s already there? Just not labeled with the “DX”? I fixed the label for the next release.
