### ISSUE TITLE
Overkill wrong cropping

### ISSUE THREAD

**Issue by rsn8887** [amigavision/AmigaVision#157]
Overkill is cropped too much, so that the status bar is not fully visible:
![20240119_202804-screen](https://github.com/amigavision/AmigaVision/assets/13071547/3bfa7b7e-289e-4a1c-8889-c9f23042d422)

**Comment by rsn8887** [comment]
Never mind I accidentally saved config, which saved previous wrong cropping.

**Comment by rsn8887** [comment]
Not even the "Force PAL" option fixes this game cropping.

**Comment by limi** [comment]
Yeah, something else is going on here. This game seems to make extreme use of the overscan area? 

I pulled it down 10px, so the HUD is fully visible; hopefully this doesn’t affect the game on other stages, as I am stealing some pixels from the bottom of the screen. This is running at 4×PAL, not even 5×PAL, and still overflows.
