### ISSUE TITLE
Superhires detail missing in Super Stardust AGA. Solution: Pixel Clock default should be 28 MHz.

### ISSUE THREAD

**Issue by rsn8887** [amigavision/AmigaVision#158]
Super Stardust AGA Score and life display on top left should look super detailed like this (super hires sprites) like here on my own WHDLoad install running normal Minimig core:

![Minimig_Game_](https://github.com/amigavision/AmigaVision/assets/13071547/5eb4c059-50ce-4217-8199-a8262c8eeb66)

Check the detail in the score and life display on the top left.

But when loaded in AmigaVision they look wrong, like this, no detail:

![AmigaVision_Game](https://github.com/amigavision/AmigaVision/assets/13071547/54a9d2dc-a1fd-402d-b3fe-9df995771282)

You can also see it immediately looking at the arrow in the title menu:

My install, standard minimig:

![Minimig_Title](https://github.com/amigavision/AmigaVision/assets/13071547/ad735d81-ccb5-4df5-9b57-59b0103f4042)

In AmigaVision, the arrow looks wrong, missing superhires detail again:

![AmigaVision_Title](https://github.com/amigavision/AmigaVision/assets/13071547/46e2d11c-b525-4f9d-a22a-c801528a6464)

In my own WHDLoad install (same slave and game version), it looks correct, and floppy version also looks correct. I am using same MiSTer.ini config, same core version, same slave and WHDLoad version in all cases.

Only AmigaVision looks wrong.

Maybe it is a consequence of cropping? I tried Force PAL, but the problem remains.

**Comment by rsn8887** [comment]
Found the fix: For AmigaVision, I need to use Pixel Clock: "28 MHz", not "adaptive." Then it works. In my own install, this setting doesn't matter.

**Comment by limi** [comment]
Yeah, Super Stardust is one of the few (the only?) games that use Super Hi-Res. Will investigate and see if we can make that the new default without hurting other games.

Appreciate the detailed report!

**Comment by limi** [comment]
28MHz is the default in the upcoming release. Thanks!
