### ISSUE TITLE
Game/Music too fast for NTSC/PAL60 Titles

### ISSUE THREAD

**Issue by synrais** [amigavision/AmigaVision#160]
When searching online for Puzznic Amiga music, every one I find is the slower music, not fast like the NTSC/60 patched version on AmigaVision.
This is a song that was written and only available for Amiga I am pretty sure.
[Amiga Puzznic](https://www.youtube.com/watch?v=9FnWvm9RWmo&list=PL5OZqGJNojJ3dd9pjdnDl0rcauEfxj0-1&index=34&ab_channel=PlinthYT)

And here is the AmigaVision version
[AmigaVision Puzznic](https://youtu.be/GdnXMUtD7ug)

Utopia is another one I feel
[Amiga Utopia Astoria II](https://www.youtube.com/watch?v=c7RGtHOj8pM&t=874s&ab_channel=JisengSo)

Here is the NTSC SNES version of this song
[Snes Utopia Astoria II](https://youtu.be/PJcJuOm3XH0?si=TikoQ5r0QmddoY3B&t=635)

AmigaVision Remix (get your glowsticks ready)
[AmigaVision Utopia Astoria II](https://youtu.be/gZD9v43mrzM)

I should note this is on a MiSTer with the latest core and menu.

**Comment by Stoppschildgruen** [comment]
The games are incorrectly set to NTSC instead of PAL. You can change it yourself by switching from MegaAGS to the Workbench via ESC on the keyboard, opening CygnusEd (right-click on the top screen under Applications), opening the corresponding file in `AGS:Run/Game` and changing `NTSC` to `PAL` and `s=0` to `s=5`.

**OLD:**
```
...
ELSE
  ags-vadjust s=0 v=0 h=0 
  whdload >NIL: "Puzznic.Slave" NTSC BUTTONWAIT SplashDelay=$whdlspdly $whdlqtkey
  ags-vadjust
ENDIF
...
```

**NEW:**
```
...
ELSE
  ags-vadjust s=5 v=0 h=0 
  whdload >NIL: "Puzznic.Slave" PAL BUTTONWAIT SplashDelay=$whdlspdly $whdlqtkey
  ags-vadjust
ENDIF
...
```

**Comment by limi** [comment]
Utopia is fixed in https://github.com/amigavision/AmigaVision/commit/ecc9499321734cc51c6c9ad64e0c22f18549b4f0
