### ISSUE TITLE
Enhancement request: allow the ability to delete entries in the frontend.

### ISSUE THREAD

**Issue by theshinyknight** [amigavision/AmigaVision#161]
Would be great to be able to remove/delete entries from the main frontend.

Currently you can add favorites, but that get out of hands pretty easily (and you can import duplicates, so it is not ideal); while there is no way to remove an entry.

There are many games that you may not play, and those could be removed directly in the interface, as you use the frontend. Either the entry can be deleted or the whole game/package can be deleted maybe, but the latter would be better to also trim down the overall size of the drive.

**Comment by limi** [comment]
We will not support file management from the launcher, you can do that using Directory Opus or similar tools.

You can remove a favorite by hitting the TAB key or the tertiary button when you are inside Favorites.

**Comment by theshinyknight** [comment]
Thanks; are you going to add some instructions about how to remove the entries from the frontend via DOpus or similar? Without knowing what elements compose the entry on the frontend, it is not that simple to delete it. Thank you

**Comment by limi** [comment]
The Favorites are in `Saves:WHDSaves`, the non-custom ones are in `AGS:`. Documentation for AGS can be found here: https://github.com/MagerValp/ArcadeGameSelector
