### ISSUE TITLE
Apocalypse PAL not PAL60

### ISSUE THREAD

**Issue by Stoppschildgruen** [amigavision/AmigaVision#163]
The game Apocalypse is incorrectly set to PAL60 / NTSC instead of PAL. If you fly the helicopter to the bottom of the screen, the screen goes completely black. This does not happen with PAL.

For those who want to correct it on their own: Switch from MegaAGS to the Workbench via ESC on the keyboard, open CygnusEd (right-click on the top screen under Applications), open the corresponding file in `AGS:Run/Game` and change `NTSC` to `PAL` and `s=0` to `s=5`.

**OLD:**
```
ELSE
  ags-vadjust s=0 v=10 h=0
  whdload >NIL: "Apocalypse.Slave" NTSC BUTTONWAIT SplashDelay=$whdlspdly $whdlqtkey
  ags-vadjust
```

**NEW:**
```
ELSE
  ags-vadjust s=5 v=10 h=0
  whdload >NIL: "Apocalypse.Slave" PAL BUTTONWAIT SplashDelay=$whdlspdly $whdlqtkey
  ags-vadjust
```

**Comment by limi** [comment]
Fixed in https://github.com/amigavision/AmigaVision/commit/ecc9499321734cc51c6c9ad64e0c22f18549b4f0
