### ISSUE TITLE
Chicago 90 5xPAL

### ISSUE THREAD

**Issue by Stoppschildgruen** [amigavision/AmigaVision#164]
The game Chicago 90 is incorrectly set to 0x and not 4x as stated. But 5x looks even better.

For those who want to correct it on their own: Switch from MegaAGS to the Workbench via ESC on the keyboard, open CygnusEd (right-click on the top screen under Applications), open the corresponding file in `AGS:Run/Game` and change `s=0` to `s=5` and `v=0` to `v=20`.

**OLD:**
```
ELSE
  ags-vadjust s=0 v=0 h=0 
  whdload >NIL: "Chicago90.Slave" PAL BUTTONWAIT SplashDelay=$whdlspdly $whdlqtkey
  ags-vadjust
```

**NEW:**
```
ELSE
  ags-vadjust s=5 v=20 h=0 
  whdload >NIL: "Chicago90.Slave" PAL BUTTONWAIT SplashDelay=$whdlspdly $whdlqtkey
  ags-vadjust
```

**Comment by synrais** [comment]
Please document all changes you make, it will help fix these speed/region issues with the modified titles.

**Comment by limi** [comment]
0 just means normal PAL— not 0×, by the way :)
