### ISSUE TITLE
Stops Working After Power Removed

### ISSUE THREAD

**Issue by EkDor** [amigavision/AmigaVision#179]
My Mister AmigaVision install works fine when installed. If I remove power from the MiSTer and then plug it back after a few seconds it will no longer work. If I click on one of the Amiga(mgl) files it just flashes and returns to the FAT directory. If I run an Update_All on the Mister AmigaVision will work again. Rinse and repeat. 

While it is working, a soft or cold reset does not break it. Something about the removal of the power supply.

Sorry if this has been reported. I did a quick search and didn't find anything on it.

-Amend - AmigaVision v2024.04.04

Thanks. - Brook

**Comment by limi** [comment]
This seems like a bug that is caused by something outside of AmigaVision — it could be SD card corruption, it could be something that `update_all` is or isn’t doing, a bit hard to know, so narrowing it down a bit should help. Do you have a second SD card that you could do a clean MiSTer install and setup on?

**Comment by EkDor** [comment]
I have just bought two new ones for the MiSTer as it happens. Will give it a shot…

(time passed here) 

Ok Created a new MiSTer install on new SD card and copied my files and settings over. It does appear to be ok now. Interesting it only seemed to affect the AmigaVision and non of the other Roms. Thanks.

Regards;
Brook Gerard 
____________________________________
 

On 25 Apr 2024, at 2:58 PM, Alex Limi ***@***.***> wrote:


This seems like a bug that is caused by something outside of AmigaVision — it could be SD card corruption, it could be something that update_all is or isn’t doing, a bit hard to know, so narrowing it down a bit should help. Do you have a second SD card that you could do a clean MiSTer install and setup on?

**Comment by limi** [comment]
Glad to hear you got it working!
