### ISSUE TITLE
Archipelagos crashing on quit

### ISSUE THREAD

**Issue by sprudel79** [amigavision/AmigaVision#181]
Hi there,
thank you so much for this wonderful project!
I use latest AmigaVision 2024.04.04  and have detected an issue with the game "Archipelagos" that I'd like to share. 
I would like to quit the game to save the current progress, however the game freezes when I press the DELETE key.
This happens both on my MISTER as well as in FS-UAE emulator.

**Comment by limi** [comment]
Since this is not related to AmigaVision, I filed an upstream bug for you:
http://mantis.whdload.de/view.php?id=6499

Subscribe/monitor that bug for any fixes.

**Comment by limi** [comment]
This has been fixed upstream, and will have the updated configuration for the next release.
