### ISSUE TITLE
Add OCS version of James Pond 2: Codename RoboCod

### ISSUE THREAD

**Issue by rhester72** [amigavision/AmigaVision#187]
The AGA version is already part of AmigaVision, but the OCS version (also supported by WHDLoad) is very different with an entirely different level set and would be nice to be supported (in addition to being what most people remember!).

If both could be supported, that would be perfect.

**Comment by limi** [comment]
If they are substantially different, that’s certainly something we could look at doing.

**Comment by rhester72** [comment]
The level design is _completely_ different for all levels.  I was quite thrown off playing the AGA version for the first time, it was almost unrecognizable :)

**Comment by limi** [comment]
Then we should add it. Thanks for the heads-up!
