### ISSUE TITLE
Request - Possible compatibility for Miyoo Mini (RetroArch) 

### ISSUE THREAD

**Issue by RudyAlbertoAcostaMarmalade** [amigavision/AmigaVision#193]
Hi there,  thank you for your amazing work on  Amiga Vision/ MegaAGS for MiSTer it's pretty much the only content I use on the device.

I was hoping you might know or be able to assist with getting the 'MegaAGS-Pocket'  version of AmigaVision working on a Miyoo Mini, or any other linux handheld that uses RetroArch.  From my attempts, it seems to me that the requirement for the 'MegaAGS-Kickstart.rom' means that some of the available emulators on RetroArch will not boot the 'MegaAGS-Pocket.hdf' as they require specific hardcoded Kickstarts.

I was wondering if you had any experience / joy in getting AmigaVision working on these RetroArch powered devices.

All the best.

**Comment by limi** [comment]
There is no Pocket-specific version anymore, as the majority of the platforms can handle 4GB+ image files either via exFAT or ext4. I have used my personal setup on an Anbernic RG35XX H (these names 🙄) using the `puae2021` for the best results so far, but we are also working with the author of Amiberry to see if we can make it even better.

Closing this issue as we are tracking this in #184.
