### ISSUE TITLE
Add CD32 support

### ISSUE THREAD

**Issue by limi** [amigavision/AmigaVision#194]
We made an experimental test setup for CD32 when CDDA support landed in the MiSTer Minimig core.

We should see if there’s a clean way to integrate it in the launcher (and explore what that means for e.g. emulator use).

**Comment by niallquinn71** [comment]
Nice!  It;s a mxied bag, really wish the CDTV games worked, or worked better.  Really wanted to hear the CDDA music in DOTC, and Xenon 2 :)   Thanks for the work your putting into this.  Cheers.

**Comment by limi** [comment]
Yeah, the “emulator” does not really support CDTV (even though some games run), it’s written for CD32 games.

**Comment by niallquinn71** [comment]
Nice one!
