### ISSUE TITLE
Path for cd32 chd files

### ISSUE THREAD

**Issue by Toryalai1** [amigavision/AmigaVision#198]
Hi,
Thank you for maintaining this project.
I have a question which is not really clear in the documentation, but where do we put the cd32 chd files? I'm using a MiSTer.

**Comment by limi** [comment]
Wherever you want. MiSTer defaults to the `games/Amiga` directory when you mount a disc, but e.g. I put mine in a separate  AmigaCD32 directory.

**Comment by limi** [comment]
Since you have a file browser in the drive select dialog, you can put them anywhere you want.
