### ISSUE TITLE
Scrambled Analog Output

### ISSUE THREAD

**Issue by owlnonymous** [amigavision/AmigaVision#199]
I'm getting a Scrambled Analog Output on my PVM with the 8.18 AV setup. I tried using the amiga.cfg from the old release and I get the same result. Any suggestions?

**Comment by limi** [comment]
We don’t touch the analog output in general, and I am somewhat certain that it has not changed since 2024.06.06. Does your PVM support 50hz input?

**Comment by owlnonymous** [comment]
Problem fixed. I had Amiga and Minimig configurations in mister.ini. Removed the Minimig lines and everything is good now.
