### ISSUE TITLE
2 games that do not boot (software failure)

### ISSUE THREAD

**Issue by NightshadowPT** [amigavision/AmigaVision#205]
I was testing some of the games I have in physical format, and I found 2 games that always seem to generate a Software Failure:

Tanks Furry (OCS)[en]
Bridge Strike (OCS)[en]

One of them (I believe it's Tank's Fury, loads the Trainer, but then boom... software Failure!

Not sure if there's anything I need to do differently, but these are the only 2 games (until now) that have not worked on the latest AmigaVision.

**Comment by limi** [comment]
Both of the games seem to work here. Sometimes, the core can get into a weird state (just like the original hardware!) if you don’t do a hard reset before starting a game. Try with a fresh boot and see if you are still having problems? (Also ensure you are running with 020 + D-Cache OFF + >8MB FastRAM)
