### ISSUE TITLE
Simon the Sorcerer has a hi-res mode

### ISSUE THREAD

**Issue by limi** [amigavision/AmigaVision#64]
If launched from the officially installed version instead of WHDLoad, it seems to support high-res mode:
https://amitopia.com/amiga-pal-high-res-games-is-a-unknown-rarity/

Potentially, we could also promote it to DBLPAL by using this tool to avoid the interlace interference:
http://aminet.net/package/util/cdity/PromoteView

`PromoteView a9004` from CLI before running the game (may need to find a way to unload it too)

**Comment by Optiroc** [comment]
As far as I can tell running it in hires interlace simply doubles the pixels.
