### ISSUE TITLE
Add Hired Guns (Demo)

### ISSUE THREAD

**Issue by keungk** [amigavision/AmigaVision#69]
as its a completely different to the release version.

**Comment by limi** [comment]
I believe the WHDLoad installer already supports that, as it says in the docs:

Note:
> In tooltypes, you can use:
> - for demo only: [CUSTOM1](http://whdload.de/docs/en/opt.html#Custom)=0 Campaign Demo (1 player)
>                         =1 Action demo (2 players)
>                         =2 Attract mode

Let me know if this is not the thing you are talking about, or if you need some help in how to set tooltypes on the Amiga :)

**Comment by keungk** [comment]
i think its one installer and two separate games. Whdownload site has them as separate downloads

**Comment by limi** [comment]
OK, I’ll take a look.

**Comment by Optiroc** [comment]
Added
