### ISSUE TITLE
Add `killaga` to Bacteria

### ISSUE THREAD

**Issue by limi** [amigavision/AmigaVision#72]
The “Bacteria” music disk fails when run from the normal WHDL setup, but works if you switch to ECS in MiSTer.

Would the general WB1.3 setup that we use for some of the disk mags be able to address this?

**Comment by Optiroc** [comment]
Nope

**Comment by limi** [comment]
Re-opening since we now know that it works with `killaga "whdload Bacteria.slave"` will fix the issue.

**Comment by Optiroc** [comment]
Fixed
