### ISSUE TITLE
Some excellent PD freeware games could be added

### ISSUE THREAD

**Issue by rsn8887** [amigavision/AmigaVision#76]
For example, the fantastic freeware games 
**Babeanoid 2,
Air Taxi,
and
Cybersphere Plus**
could be added.

Download for those three freeware games:
https://www.mediafire.com/file/e9rmcfdp67sqkr6/amigapd.zip/file

**Age of Rock** is really good too, now that I think of it. Download:
https://www.mediafire.com/file/q6mr05nspob94v5/AgeRock-WHDL.lha/file

### Gameplay footage

Babeanoid 2:
https://www.youtube.com/watch?v=q56sjbq9qQE

Air Taxi, which can be played with 5 players simultaneously:
https://youtu.be/Z7fHJtLUm1Y

Cybersphere Plus:
https://youtu.be/TR8r1ZqOLAA

Age of Rock is like Quarth but with 3 player simultaneous team and vs modes:
https://www.youtube.com/watch?v=G-8BU_fdtl0

### More Info

The are thousands more PD games that have been converted to WHD in the Aladin Generic WHDLoad collection. More info here:
https://eab.abime.net/showthread.php?p=1124581#post1124581

Most of them are not that great, but a few of them amazing.

**Comment by Optiroc** [comment]
Thanks for the suggestions!

Cybersphere Plus and Age of Rock looks worth playing, I'll probably add those. 👍

Might go for Air Taxi too, since it's rare and pretty cool with >2 player games.

As for the Aladin collection. I've added a select few of those back when the MegaAGS collection started, and adding any more will be on a case-by-base basis.

**Comment by rsn8887** [comment]
I just learned that there's a prequel to Cybersphere Plus, just called Cybersphere which is also cool:
https://www.mediafire.com/file/zm902qm8tt5xz0q/Cybersphere-WHDL.lha/file

Might be good to add both Cybersphere and its sequel Cybersphere Plus. Both are cool, just with different levels.
