### ISSUE TITLE
Poing has a newer version, 7.14

### ISSUE THREAD

**Issue by rsn8887** [amigavision/AmigaVision#77]
The version of Poing included is an older version, 7.00.

There is a newer version, 7.14, which has a level select screen and more levels:

https://www.mediafire.com/file/ba44iljt1t4u9fj/poing714.lha/file

More information is on the English Amiga Board:
https://eab.abime.net/showthread.php?t=102817&highlight=poing

**Comment by Optiroc** [comment]
Done
