### ISSUE TITLE
Zoom settings from AmigaVision also affect other configurations

### ISSUE THREAD

**Issue by rsn8887** [amigavision/AmigaVision#78]
After running AmigaVision, my own personal Amiga configurations are still affected by the last crop config that was active in AmigaVision. I don't fully understand why this is, since AmigaVision is now using .mgl files, which should remedy this problem.

In order to reset the crop for my own configurations, I have to manually delete the two "shared/Miminig_vadjust.dat" and "shared/Amiga_vadjust.dat" files every time after I run AmigaVision.

I have tested various sequences of running the .mgl for AmigaVision and then the minimig core directly for my own configurations, but nothing seems to help with this, apart from deleting those files.

I also tested crop with .mgl a bit more and it seems that, in general, the minimig core always loads the crop config from a hardcoded location "games/Amiga/shared/minimig_vadjust.dat".

It would be great if it loaded "games/[setname]/shared/[setname]_vadjust.dat" instead. This would allow full isolation of different setnames from each other. in completely different directories. This would also be more consistent with other aspects of how mgl files and setnames work.

**Comment by rsn8887** [comment]
Since the isolation between AmigaVision configs and personal configs works pretty well already, it might be good to not ship AmigaVision with a "minimig.cfg". It already comes with Amiga.cfg and the corresponding .mgl, which is enough. 

I have several friends who destroyed their own personal startup config by copying over the AmigaVision minimig.cfg over their own.

**Comment by Optiroc** [comment]
The clashing of the Amiga `setname` that is used both when loading the "raw" minimig.rbf and the Amiga.mgl we now use for MegaAGS was a huge woe that easily delayed this release for at least two months... :D Indeed, it would be best to use a non-clashing setname.

**Comment by limi** [comment]
As mentioned in #81, the next release will not include anything related to `minimig*`on the config front, so should address this. 

And, as with that issue, this is not new, and older versions of MegaAGS would also do this, but we can avoid it now that we have the new MGL setup, agreed.
