### ISSUE TITLE
Demo - Hardwired - Graphics Corruption

### ISSUE THREAD

**Issue by M-Walrus** [amigavision/AmigaVision#86]
The "Jelle-Vectors" segment with the green cube about 3/4 through the demo has graphical corruption.  The rest seems to run correctly.

Amiga.Vision/MegaAGS version tested: 2023-04-04

**Comment by Optiroc** [comment]
This is due to a timing issue with the AGA mode of Minimig that effects a relatively big number of demos, and a few games. In severe cases we add a note to the info box, or exclude them.
