### ISSUE TITLE
Suggested additions to "French Touch" Focus list

### ISSUE THREAD

**Issue by Newsdee** [amigavision/AmigaVision#89]
There are quite a few more French interesting and iconic games that could be added to the "French Touch" section:

_[Publisher: Ubi Soft]_
B.A.T.
Puffy's Saga
Unreal
Zombi

_[Publisher: Cryo]_
Dune
KGB
Extase

_[Publisher: Titus]_
Lamborghini American Challenge
Titus the Fox
The Brainies
Blues Brothers
Prehistorik
Super Cauldron
Knight Force

_[Publisher: Silmarils]_
Bunny Bricks
Boston Bomb Club
Ishar 3
Robinson's Requiem
Transarctica
Targhan

_[Publisher: Lankhor]_
Vroom
Maupiti Island
Mortville Manor
G. Nius
Black Sect
Outzone

_[Publisher: ERE Informatique]_
Captain Blood
Kult
Purple Saturn Day
Warlock’s Quest
Crash Garrett
Teenage Queen
Billiards Simulator

_[Publisher: Coktel Vision]_
Bargon Attack
Geisha
Gobliiins
Ween: The Prophecy

_[Publisher: Infomedia]_
Chrono Quest II

**Comment by Optiroc** [comment]
Thanks for the suggestions! “French touch” is more of a vibe than a declaration of origin, but many of these definitely fit!
