### ISSUE TITLE
Extend `title_short` launcher display from 27 to 29/30 characters

### ISSUE THREAD

**Issue by limi** [amigavision/AmigaVision#94]
Going through the top lists, it struck me that we are not fully displaying the proper names for a number of the most popular games on Amiga when the ranking numbers are added.

Currently, I believe the *display limit* is 27 characters, but just upping that limit to 29 or 30 characters instead should take care of most of them, examples:

```
040 It Came from the Desert
001 Sensible World of Soccer
024 Ultimate Soccer Manager
004 Secret of Monkey Island
057 Four Crystals of Trazere
047 World Class Leader Board
048 Arkanoid: Revenge of Doh
008 Premier Manager 3 Deluxe
050 Shadow of the Beast III
```

…versus the current situation:

```
040 It Came from the Des..
006 Sensible World of So..
024 Ultimate Soccer Mana..
048 Secret of Monkey Isl..
057 Four Crystals of Tra..
047 World Class Leader B..
048 Arkanoid: Revenge of..
008 Premier Manager 3 De..
000 Shadow of the Beast ..
```

There does seem to be enough space to do this in the current medium-resolution layout — of course, the `skin-bg.iff` file would have to be updated, and some offsets for where to position the thumbnail images would have to be adjusted accordingly.

**Comment by limi** [comment]
It’s funny how most Amiga game titles fit into 25 characters (+ the 4 needed for the ranking), wondering if there was a standard `char(25)` entry for game titles among retailers or something.

**Comment by Optiroc** [comment]
This needs support in AGS2. The current setting is the maximum supported width.

**Comment by Optiroc** [comment]
Done in 1c7004ee253cf6ea67e96822179b530a756321a7

(AGS2 changes in https://github.com/Optiroc/ArcadeGameSelector/commit/f2543ab7e3a001c65833d8e00a51dc248b67b7df)
