### ISSUE TITLE
Add support for Genesia / Ultimate Domain

### ISSUE THREAD

**Issue by tmznix** [amigavision/AmigaVision#97]
Hi team, I am back with another request.

If possible, please add support for Genesia (Microïds)

WHDLoad is here: https://www.whdload.de/games/Genesia.html

![](https://cdn.mobygames.com/screenshots/16075555-ultimate-domain-amiga-zoom-on-one-particular-sector-of-the-world.png)

Thank you in advance.
Cheers!

**Comment by Optiroc** [comment]
For some reason this WHDL install didn’t work on Minimig_MiSTer last time I checked so it’s been marked not to be included. I can check again and try some configuration options.
